---
name: lint
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3
      # this must be installed to use the prettier version
      # from the package.json file.
      - name: install prettier.
        run: npm install .
      - name: verify with prettier.
        run: npx prettier --check .
      - name: verify with fix.py
        run: python scripts/fix.py --check ./aep/general/
