---
name: lint
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v3
      - name: install node.
        run: |
          apt-get update
          apt-get install -y nodejs npm
      - name: install dependencies.
        run: npm install .
      - name: run check command.
        run: npm run check
